steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', '.',
    '-t', 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/alltheplaces',
    '--build-arg', 'PROJECT_ID=${PROJECT_ID}'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'push', 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/alltheplaces'
  ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'run', 'deploy',
    '--platform', 'managed',
    'alltheplaces',
    '--image', 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/alltheplaces',
    '--memory', '128Mi',
    '--region', 'us-central1',
    '--allow-unauthenticated'
  ]
images:
- 'us-central1-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/alltheplaces'
timeout: 1800s
