steps:
- name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
  - -c
  - |
    [[ ${LOCATION} != global ]] || (echo need LOCATION != global; exit 1)
    [[ -n ${_DOCKER_REPO} ]] || (echo need _DOCKER_REPO; exit 1)
- name: gcr.io/cloud-builders/docker
  timeout: 900s
  args:
  - build
  - .
  - -t
  - ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/alltheplaces
  - --build-arg
  - PROJECT_ID=${PROJECT_ID}
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/alltheplaces
- name: gcr.io/cloud-builders/gcloud
  args:
  - run
  - deploy
  - alltheplaces
  - --allow-unauthenticated
  - --platform
  - managed
  - --image
  - ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/alltheplaces
  - --memory
  - 128Mi
  - --region
  - ${LOCATION}
images:
- ${LOCATION}-docker.pkg.dev/${PROJECT_ID}/my-docker-repo/alltheplaces
timeout: 1800s
options:
  machineType: E2_HIGHCPU_8
