steps:
- name: gcr.io/cloud-builders/docker
  timeout: 900s
  args:
  - build
  - .
  - -t
  - ${_ARTIFACTS_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACTS_REPOSITORY}/alltheplaces
  - --build-arg
  - BUILDER_IMAGE=${_ARTIFACTS_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACTS_REPOSITORY}/alltheplaces-builder
- name: gcr.io/cloud-builders/docker
  args:
  - push
  - ${_ARTIFACTS_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACTS_REPOSITORY}/alltheplaces
- name: gcr.io/cloud-builders/gcloud
  args:
  - run
  - deploy
  - alltheplaces
  - --allow-unauthenticated
  - --platform
  - managed
  - --image
  - ${_ARTIFACTS_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACTS_REPOSITORY}/alltheplaces
  - --memory
  - 512Mi
  - --region
  - ${_RUN_REGION}
- name: gcr.io/${PROJECT_ID}/firebase
  args:
  - deploy
  - --project=${PROJECT_ID}
  - --only=hosting
images:
- ${_ARTIFACTS_LOCATION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACTS_REPOSITORY}/alltheplaces
timeout: 1800s
substitutions:
  _ARTIFACTS_LOCATION: us-central1
  _ARTIFACTS_REPOSITORY: my-docker-repo
  _RUN_REGION: us-central1
options:
  machineType: E2_HIGHCPU_8
